### ISSUE TITLE
Getting Niddler working in Flutter app with IntelliJ Plugin

### ISSUE THREAD

**Issue by CTHRU** [Chimerapps/niddler_dart#10]
Hi,

I tried to integrate niddler_dart into a Flutter project I'm working on in IntelliJ (Community Edition).
I'm on Flutter Channel master, 1.22.0-10.0.pre.340 and running an App in an Android eumlator.

Probably because I'm on the Flutter master, I had to make a small change the 0.9.1 sources due to an error that the abort() method from HttpClientRequest wasn't implemented in class _NiddlerHttpClientRequest. I just added an empty stub to test by adding the following lines in platform.io.niddler_dart.dart, line 491.

>  @override
>  void abort([Object exception, StackTrace stackTrace]) => () {};

I then copied from your example and added the code to my main() method.

>  await Chain.capture(() async {
>    final niddlerBuilder = NiddlerBuilder()
>      ..bundleId = '<my app>'
>      ..serverInfo = NiddlerServerInfo(
>          '<my name>', '<my description>', icon: 'dart')
>      ..includeStackTrace = true
>      ..port = 0; //0 to have niddler pick it's own port. Automatic discovery will make this visible
>
>    final niddler = niddlerBuilder.build()..addBlacklist(RegExp('.*/get'));
>
>    await niddler.start(waitForDebugger: true);
>
>    niddler.install();
>  });

I can successfully select and connect the application in the Niddler plugin in IntelliJ when it is started in the Android emulator (Pixel 2 Android ~~29~~28).

I then did some actions in the app that perform a http POST request and a response came back from the server. Unfortunately I don't see anything in the Niddler plugin ('Nothing to show'). 

I would appreciate your help if you have an idea where I went wrong.

Thanks in advance.

**Comment by vanlooverenkoen** [comment]
Now that Flutter 1.22 has landed we have the same problem on stable

**Comment by NicolaVerbeeck** [comment]
Should be fixed in 0.10.0
