### ISSUE TITLE
Very slow likely due to Isolate usage

### ISSUE THREAD

**Issue by kuhnroyal** [Chimerapps/niddler_dart#13]
When using the package in debug mode, my request take a lot longer.
For bigger response bodies my HTTP proxy has a request/response time of 700ms in the log and Niddler has 7 seconds.
This is due to the processing of the JSON which is incorporated into the timings, and the response gets encoded/decoded twice, once by DIO and then again by Niddler.

But even on very small responses, there is a huge overhead due to spawning of the isolate for encoding.
A small improvement would probably be to keep the isolate alive and reuse it.

An even bigger improvement would be to somehow find a way to reuse the existing JSON body from response to completely avoid the encoding step.

**Comment by NicolaVerbeeck** [comment]
Niddler does not parse your body json, niddler creates a json message containing the raw body of the request. I agree that we need to optimize the isolate code though.

**Comment by NicolaVerbeeck** [comment]
A change has been made in 1.4.0, please try to see if this helps

**Comment by kuhnroyal** [comment]
This is a lot faster, still much slower than without but a great improvement.

There are some lateinit errors flying around from the worker_manager, not directly reproducible.

```
LateError: LateInitializationError: Field '_sendPort@3683091195' has not been initialized.
  File "worker_io.dart", in WorkerImpl._sendPort
  File "worker_io.dart", line 46, col 5, in WorkerImpl.work
  File "executor.dart", line 144, col 22, in _Executor._schedule
  File "executor.dart", line 113, col 9, in _Executor.execute.executing
  File "executor.dart", line 122, col 12, in _Executor.execute
  File "niddler_dart.dart", line 592, col 8, in _encodeBody
  File "niddler_dart.dart", line 544, col 5, in _NiddlerHttpClientRequest._handleDefaultResponse
  File "niddler_dart.dart", line 431, col 16, in _NiddlerHttpClientRequest._handleResponse.<fn>
  File "zone.dart", line 1434, col 47, in _rootRunUnary
  File "zone.dart", line 1335, col 19, in _CustomZone.runUnary
  File "<asynchronous suspension>"
  File "niddler_dart.dart", line 403, col 31, in _NiddlerHttpClientRequest.close
```

**Comment by NicolaVerbeeck** [comment]
Hmm, the worker manager was not a good fit then if it has errors. I will have to brew up something custom when I find the time. I will make a ticket for this and fix it later (today) when I find some time

**Comment by NicolaVerbeeck** [comment]
The slowdown is now likely caused by the fact that niddler needs to get the response fully before passing it on, no data streaming is allowed. Are you using the debugger to connect? Because that will also wait for the json message to be generated

**Comment by kuhnroyal** [comment]
Not using the debugger so far. But it is actually a lot faster than before, nice work. Thanks!

**Comment by kuhnroyal** [comment]
> Hmm, the worker manager was not a good fit then if it has errors. I will have to brew up something custom when I find the time. I will make a ticket for this and fix it later (today) when I find some time

I can monitor this before you do anything. Maybe this is related to a hot restart before.

**Comment by NicolaVerbeeck** [comment]
I replaced the worker manager with Computer which I have more experience with. This is now in 1.4.1

**Comment by kuhnroyal** [comment]
Working well so far, thanks!
