### ISSUE TITLE
Flutter for web support

### ISSUE THREAD

**Issue by vanlooverenkoen** [Chimerapps/niddler_dart#2]
With the release of Flutter 1.9. Flutter for web was merged in the main library. Because flutter for web can not work with dart:io. Niddler_dart is not supported for Flutter for web.

 Not sure if it should be fixed right away or wait for the official release of flutter for web.

`Browser-based applications can't use this library. Only servers, command-line scripts, and Flutter mobile apps can import and use dart:io.`

https://api.dartlang.org/stable/2.5.0/dart-io/dart-io-library.html

**Comment by NicolaVerbeeck** [comment]
Fixed in #3
